name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew buildFatJar
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 90
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/}
      - name: Upload Artifact to Release
        run: gh release upload  ${GITHUB_REF#refs/*/} build/libs/*.jar
